"""Creacion inicial de tablas

Revision ID: 22af02a67c67
Revises: ceb097627058
Create Date: 2026-06-12 12:27:26.534003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22af02a67c67'
down_revision: Union[str, Sequence[str], None] = 'ceb097627058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lienzos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('version_lienzo', sa.Integer(), nullable=False),
    sa.Column('esta_bloqueado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proyecto_id')
    )
    op.create_table('nodos_lienzo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lienzo_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('etiqueta', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('parametros_configuracion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('es_obligatorio', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lienzo_id'], ['lienzos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bordes_lienzo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lienzo_id', sa.Uuid(), nullable=False),
    sa.Column('nodo_origen_id', sa.Uuid(), nullable=False),
    sa.Column('nodo_destino_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_de_dato', sa.String(length=100), nullable=True),
    sa.Column('es_condicional', sa.Boolean(), nullable=False),
    sa.Column('expresion_condicional', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lienzo_id'], ['lienzos.id'], ),
    sa.ForeignKeyConstraint(['nodo_destino_id'], ['nodos_lienzo.id'], ),
    sa.ForeignKeyConstraint(['nodo_origen_id'], ['nodos_lienzo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proyecto_id', sa.Uuid(), nullable=False),
    sa.Column('nodo_lienzo_id', sa.Uuid(), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nodo_lienzo_id'], ['nodos_lienzo.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fases')
    op.drop_table('bordes_lienzo')
    op.drop_table('nodos_lienzo')
    op.drop_table('lienzos')
    # ### end Alembic commands ###
