"""add_codigos_segmento

Revision ID: 2d24bb976ce8
Revises: f67d172dd775
Create Date: 2026-06-13 23:39:20.743180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d24bb976ce8'
down_revision: Union[str, Sequence[str], None] = 'f67d172dd775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_segmento',
    sa.Column('segmento_id', sa.Uuid(), nullable=False),
    sa.Column('categoria_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['segmento_id'], ['segmentos.id'], ),
    sa.PrimaryKeyConstraint('segmento_id', 'categoria_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codigos_segmento')
    # ### end Alembic commands ###
