"""Creacion inicial de tablas

Revision ID: ceb097627058
Revises:
Create Date: 2026-06-12 12:13:53.413848

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ceb097627058"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ejecuciones_agentes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agente_id", sa.String(length=100), nullable=False),
        sa.Column("fase_id", sa.String(length=100), nullable=True),
        sa.Column("modelo_llm", sa.String(length=100), nullable=False),
        sa.Column("hash_entrada", sa.String(length=256), nullable=False),
        sa.Column(
            "payload_completo", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("costo_usd", sa.Float(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "langgraph_checkpoints",
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=255), nullable=False),
        sa.Column("parent_checkpoint_id", sa.String(length=255), nullable=True),
        sa.Column(
            "checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("thread_id", "checkpoint_id"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("correo", sa.String(length=255), nullable=False),
        sa.Column("rol", sa.String(length=50), nullable=False),
        sa.Column("plan", sa.String(length=50), nullable=False),
        sa.Column("tokens_mensuales_usados", sa.Integer(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_correo"), "usuarios", ["correo"], unique=True)
    op.create_table(
        "proyectos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("ruta_de_codificacion", sa.String(length=50), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("creador_id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creador_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categorias",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("definicion", sa.Text(), nullable=False),
        sa.Column("limites", sa.Text(), nullable=True),
        sa.Column("estado_saturacion", sa.String(length=50), nullable=False),
        sa.Column("puntaje_relevancia", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("es_central", sa.Boolean(), nullable=False),
        sa.Column(
            "embedding_centroide",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536),
            nullable=True,
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documentos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("tipo_de_fuente", sa.String(length=50), nullable=False),
        sa.Column("ruta_s3", sa.String(length=1000), nullable=True),
        sa.Column("metadatos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("autor_id", sa.Uuid(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("contenido", sa.Text(), nullable=False),
        sa.Column("es_confidencial", sa.Boolean(), nullable=False),
        sa.Column("hash_tema", sa.String(length=256), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["autor_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "doc_codes",
        sa.Column("documento_id", sa.Uuid(), nullable=False),
        sa.Column("categoria_id", sa.Uuid(), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("resumen_evidencia", sa.Text(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documentos.id"],
        ),
        sa.PrimaryKeyConstraint("documento_id", "categoria_id"),
    )
    op.create_table(
        "segmentos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("documento_id", sa.Uuid(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("parafrasis", sa.Text(), nullable=True),
        sa.Column("posicion", sa.Integer(), nullable=False),
        sa.Column("conteo_tokens", sa.Integer(), nullable=False),
        sa.Column("es_anomalia", sa.Boolean(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("segmentos")
    op.drop_table("doc_codes")
    op.drop_table("memos")
    op.drop_table("documentos")
    op.drop_table("categorias")
    op.drop_table("proyectos")
    op.drop_index(op.f("ix_usuarios_correo"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_table("langgraph_checkpoints")
    op.drop_table("ejecuciones_agentes")
    # ### end Alembic commands ###
