"""initial_schema

Revision ID: f67d172dd775
Revises:
Create Date: 2026-06-13 23:20:08.246042

"""

from typing import Sequence, Union

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f67d172dd775"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ejecuciones_agentes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agente_id", sa.String(length=100), nullable=False),
        sa.Column("fase_id", sa.String(length=100), nullable=True),
        sa.Column("modelo_llm", sa.String(length=100), nullable=False),
        sa.Column("hash_entrada", sa.String(length=256), nullable=False),
        sa.Column(
            "payload_completo", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("costo_usd", sa.Float(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "langgraph_checkpoints",
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=255), nullable=False),
        sa.Column("parent_checkpoint_id", sa.String(length=255), nullable=True),
        sa.Column(
            "checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("thread_id", "checkpoint_id"),
    )
    op.create_table(
        "processing_states",
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("step", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("entity_type", "entity_id", "step"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("correo", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column(
            "rol",
            sa.Enum(
                "INVESTIGADOR_PRINCIPAL",
                "COLABORADOR",
                "ESTUDIANTE",
                "AUDITOR",
                "VISUALIZADOR",
                name="rol_usuario_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "plan",
            sa.Enum("BASICO", "PROFESIONAL", name="plan_suscripcion_enum"),
            nullable=False,
        ),
        sa.Column("tokens_mensuales_usados", sa.Integer(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_correo"), "usuarios", ["correo"], unique=True)
    op.create_table(
        "proyectos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("ruta_de_codificacion", sa.String(length=50), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("creador_id", sa.Uuid(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["creador_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categorias",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("definicion", sa.Text(), nullable=False),
        sa.Column("limites", sa.Text(), nullable=True),
        sa.Column("estado_saturacion", sa.String(length=50), nullable=False),
        sa.Column("puntaje_relevancia", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("es_central", sa.Boolean(), nullable=False),
        sa.Column(
            "embedding_centroide",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024),
            nullable=True,
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documentos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("tipo_de_fuente", sa.String(length=50), nullable=False),
        sa.Column("ruta_s3", sa.String(length=1000), nullable=True),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("metadatos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_table(
        "graph_entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lienzos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("version_lienzo", sa.Integer(), nullable=False),
        sa.Column("esta_bloqueado", sa.Boolean(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proyecto_id"),
    )
    op.create_table(
        "memos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("autor_id", sa.Uuid(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("contenido", sa.Text(), nullable=False),
        sa.Column("es_confidencial", sa.Boolean(), nullable=False),
        sa.Column("hash_tema", sa.String(length=256), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["autor_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "code_document_summaries",
        sa.Column("code_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["categorias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documentos.id"],
        ),
        sa.PrimaryKeyConstraint("code_id", "document_id"),
    )
    op.create_table(
        "code_global_summaries",
        sa.Column("code_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["categorias.id"],
        ),
        sa.PrimaryKeyConstraint("code_id"),
    )
    op.create_table(
        "code_prototypes",
        sa.Column("code_id", sa.Uuid(), nullable=False),
        sa.Column(
            "segment_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("updated_at", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["categorias.id"],
        ),
        sa.PrimaryKeyConstraint("code_id"),
    )
    op.create_table(
        "doc_codes",
        sa.Column("documento_id", sa.Uuid(), nullable=False),
        sa.Column("categoria_id", sa.Uuid(), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("resumen_evidencia", sa.Text(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categorias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documentos.id"],
        ),
        sa.PrimaryKeyConstraint("documento_id", "categoria_id"),
    )
    op.create_table(
        "graph_relations",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("relation_type", sa.String(length=100), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["graph_entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["graph_entities.id"],
        ),
        sa.PrimaryKeyConstraint("source_id", "target_id", "relation_type"),
    )
    op.create_table(
        "hypotheses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("code_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("parent_hypothesis_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["categorias.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_hypothesis_id"],
            ["hypotheses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nodos_lienzo",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lienzo_id", sa.Uuid(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=False),
        sa.Column("etiqueta", sa.String(length=200), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column("pos_x", sa.Float(), nullable=False),
        sa.Column("pos_y", sa.Float(), nullable=False),
        sa.Column(
            "parametros_configuracion",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("es_obligatorio", sa.Boolean(), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lienzo_id"],
            ["lienzos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "saturation_metrics",
        sa.Column("code_id", sa.Uuid(), nullable=False),
        sa.Column(
            "centroid", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.Column("rolling_std", sa.Float(), nullable=False),
        sa.Column("saturation_status", sa.String(length=50), nullable=False),
        sa.Column("documents_since_change", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["categorias.id"],
        ),
        sa.PrimaryKeyConstraint("code_id"),
    )
    op.create_table(
        "segmentos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("documento_id", sa.Uuid(), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("parafrasis", sa.Text(), nullable=True),
        sa.Column("posicion", sa.Integer(), nullable=False),
        sa.Column("conteo_tokens", sa.Integer(), nullable=False),
        sa.Column("es_anomalia", sa.Boolean(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bordes_lienzo",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lienzo_id", sa.Uuid(), nullable=False),
        sa.Column("nodo_origen_id", sa.Uuid(), nullable=False),
        sa.Column("nodo_destino_id", sa.Uuid(), nullable=False),
        sa.Column("tipo_de_dato", sa.String(length=100), nullable=True),
        sa.Column("es_condicional", sa.Boolean(), nullable=False),
        sa.Column("expresion_condicional", sa.String(length=500), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lienzo_id"],
            ["lienzos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["nodo_destino_id"],
            ["nodos_lienzo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["nodo_origen_id"],
            ["nodos_lienzo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("nodo_lienzo_id", sa.Uuid(), nullable=True),
        sa.Column("numero", sa.String(length=20), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("estado", sa.String(length=50), nullable=False),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["nodo_lienzo_id"],
            ["nodos_lienzo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fases")
    op.drop_table("bordes_lienzo")
    op.drop_table("segmentos")
    op.drop_table("saturation_metrics")
    op.drop_table("nodos_lienzo")
    op.drop_table("hypotheses")
    op.drop_table("graph_relations")
    op.drop_table("doc_codes")
    op.drop_table("code_prototypes")
    op.drop_table("code_global_summaries")
    op.drop_table("code_document_summaries")
    op.drop_table("memos")
    op.drop_table("lienzos")
    op.drop_table("graph_entities")
    op.drop_table("documentos")
    op.drop_table("categorias")
    op.drop_table("proyectos")
    op.drop_index(op.f("ix_usuarios_correo"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_table("processing_states")
    op.drop_table("langgraph_checkpoints")
    op.drop_table("ejecuciones_agentes")
    # ### end Alembic commands ###
