"""cgt_refactor_phase0

Revision ID: ff33a5c05513
Revises: 0e185a3e0abb
Create Date: 2026-06-16 23:53:46.755641

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff33a5c05513"
down_revision: Union[str, Sequence[str], None] = "0e185a3e0abb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incident_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "incident_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("labeled_by_agent", sa.String(length=100), nullable=True),
        sa.Column(
            "critic_verdict", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_groups_proyecto_id"),
        "incident_groups",
        ["proyecto_id"],
        unique=False,
    )
    op.create_table(
        "memo_sorting_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("theoretical_code_id", sa.Uuid(), nullable=True),
        sa.Column(
            "groups_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "homeless_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "forced_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("thin_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["theoretical_code_id"],
            ["theoretical_codes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memo_sorting_attempts_proyecto_id"),
        "memo_sorting_attempts",
        ["proyecto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_memo_sorting_attempts_theoretical_code_id"),
        "memo_sorting_attempts",
        ["theoretical_code_id"],
        unique=False,
    )
    op.create_table(
        "extracted_incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("segmento_id", sa.Uuid(), nullable=False),
        sa.Column("documento_id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("jot_text", sa.Text(), nullable=True),
        sa.Column("keep_moving", sa.Boolean(), nullable=False),
        sa.Column("tipo_dato_glaser", sa.String(length=50), nullable=True),
        sa.Column(
            "preguntas_glaser_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("patrón_documento_id", sa.Uuid(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["documento_id"],
            ["documentos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patrón_documento_id"],
            ["document_processes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["segmento_id"],
            ["segmentos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_extracted_incidents_documento_id"),
        "extracted_incidents",
        ["documento_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extracted_incidents_proyecto_id"),
        "extracted_incidents",
        ["proyecto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extracted_incidents_segmento_id"),
        "extracted_incidents",
        ["segmento_id"],
        unique=False,
    )
    op.create_table(
        "memo_sorting_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column(
            "memos_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "cross_family_affinity_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["memo_sorting_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memo_sorting_groups_attempt_id"),
        "memo_sorting_groups",
        ["attempt_id"],
        unique=False,
    )
    op.create_table(
        "incident_comparisons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_a_id", sa.Uuid(), nullable=False),
        sa.Column("incident_b_id", sa.Uuid(), nullable=False),
        sa.Column("proyecto_id", sa.Uuid(), nullable=False),
        sa.Column("similarity_score", sa.Float(), nullable=False),
        sa.Column("are_interchangeable", sa.Boolean(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "creado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actualizado_en", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_a_id"],
            ["extracted_incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_b_id"],
            ["extracted_incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_comparisons_proyecto_id"),
        "incident_comparisons",
        ["proyecto_id"],
        unique=False,
    )
    # ── F0 preserve: estas tablas existen en BD pero no en modelos ──
    # op.drop_index(op.f('idx_loop_logs_agent'), table_name='agent_loop_logs')
    # op.drop_index(op.f('idx_loop_logs_proyecto'), table_name='agent_loop_logs')
    # op.drop_table('agent_loop_logs')
    # op.drop_index(op.f('idx_agent_outputs_agent'), table_name='agent_outputs')
    # op.drop_index(op.f('idx_agent_outputs_proyecto'), table_name='agent_outputs')
    # op.drop_index(op.f('idx_agent_outputs_ref'), table_name='agent_outputs')
    # op.drop_table('agent_outputs')
    # op.drop_index(op.f('idx_modifications_output'), table_name='output_modifications')
    # op.drop_index(op.f('idx_modifications_proyecto'), table_name='output_modifications')
    # op.drop_table('output_modifications')
    # op.drop_table('agent_families')
    op.add_column(
        "categorias",
        sa.Column(
            "saturation_panel_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.add_column(
        "categorias", sa.Column("gerundio_label", sa.String(length=200), nullable=True)
    )
    op.alter_column(
        "category_definition_versions",
        "properties_at_version",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "category_definition_versions",
        "incident_count_at_version",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "category_definition_versions",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conceptual_relationships",
        "category_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "elaboration_status",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "converging_incident_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "converging_doc_count",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "diverging_incident_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "diverging_doc_count",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "origin_memo_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "origin_hypothesis_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "conceptual_fit",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "position_tension",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "conceptual_relationships",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "documentos",
        "estado",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_server_default=sa.text("'crudo'::character varying"),
    )
    op.alter_column(
        "ecosystem_layouts", "version", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "ecosystem_layouts",
        "blob_positions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "ecosystem_layouts",
        "ghost_positions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "ecosystem_layouts",
        "fog_zones",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "ecosystem_layouts",
        "physics_params",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "ecosystem_layouts",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "elaboration_memos",
        "ecosystem_snapshot",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "elaboration_memos",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "memos",
        sa.Column("version", sa.Integer(), nullable=False, server_default=sa.text("1")),
    )
    op.add_column("memos", sa.Column("parent_memo_id", sa.Uuid(), nullable=True))
    op.add_column(
        "memos",
        sa.Column(
            "structured_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_foreign_key(None, "memos", "memos", ["parent_memo_id"], ["id"])
    op.drop_index(op.f("idx_paradigm_states_code_iter"), table_name="paradigm_states")
    op.drop_index(op.f("idx_paradigm_states_proyecto"), table_name="paradigm_states")
    op.add_column(
        "proyectos", sa.Column("coding_style_instruction", sa.Text(), nullable=True)
    )
    op.add_column(
        "proyectos",
        sa.Column(
            "object_of_study",
            sa.String(length=50),
            nullable=False,
            server_default=sa.text("'concern'::character varying"),
        ),
    )
    op.drop_index(
        op.f("idx_segmentos_embedding_hnsw"),
        table_name="segmentos",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_index(
        op.f("idx_segmentos_texto_tsv"), table_name="segmentos", postgresql_using="gin"
    )
    op.drop_column("segmentos", "texto_tsv")
    op.alter_column(
        "theoretical_codes", "glaserian", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "theoretical_codes", "user_defined", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "theoretical_codes",
        "evaluation_logic",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "theoretical_codes",
        "output_schema",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "theoretical_codes",
        "compatible_with",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "theoretical_codes",
        "layer",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "theoretical_codes",
        "visualization_hint",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "theoretical_codes",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "theoretical_codes",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "theoretical_codes",
        "visualization_hint",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "theoretical_codes", "layer", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "theoretical_codes",
        "compatible_with",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "theoretical_codes",
        "output_schema",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "theoretical_codes",
        "evaluation_logic",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "theoretical_codes", "user_defined", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "theoretical_codes", "glaserian", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.add_column(
        "segmentos",
        sa.Column(
            "texto_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('spanish'::regconfig, COALESCE(texto, ''::text))",
                persisted=True,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        op.f("idx_segmentos_texto_tsv"),
        "segmentos",
        ["texto_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_segmentos_embedding_hnsw"),
        "segmentos",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_column("proyectos", "object_of_study")
    op.drop_column("proyectos", "coding_style_instruction")
    op.create_index(
        op.f("idx_paradigm_states_proyecto"),
        "paradigm_states",
        ["proyecto_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_paradigm_states_code_iter"),
        "paradigm_states",
        ["code_id", "iteration"],
        unique=False,
    )
    op.drop_constraint(None, "memos", type_="foreignkey")
    op.drop_column("memos", "structured_fields")
    op.drop_column("memos", "parent_memo_id")
    op.drop_column("memos", "version")
    op.alter_column(
        "elaboration_memos",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "elaboration_memos",
        "ecosystem_snapshot",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "ecosystem_layouts",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "ecosystem_layouts",
        "physics_params",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "ecosystem_layouts",
        "fog_zones",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "ecosystem_layouts",
        "ghost_positions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "ecosystem_layouts",
        "blob_positions",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "ecosystem_layouts", "version", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "documentos",
        "estado",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_server_default=sa.text("'crudo'::character varying"),
    )
    op.alter_column(
        "conceptual_relationships",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "conceptual_relationships",
        "position_tension",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "conceptual_relationships",
        "conceptual_fit",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "conceptual_relationships",
        "origin_hypothesis_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "conceptual_relationships",
        "origin_memo_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "conceptual_relationships",
        "diverging_doc_count",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "conceptual_relationships",
        "diverging_incident_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "conceptual_relationships",
        "converging_doc_count",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "conceptual_relationships",
        "converging_incident_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "conceptual_relationships",
        "elaboration_status",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "conceptual_relationships",
        "category_ids",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "category_definition_versions",
        "creado_en",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "category_definition_versions",
        "incident_count_at_version",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "category_definition_versions",
        "properties_at_version",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_column("categorias", "gerundio_label")
    op.drop_column("categorias", "saturation_panel_json")
    op.create_table(
        "agent_families",
        sa.Column("family", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("label", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("icon", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("research_question", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "verification_method", sa.TEXT(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "accepted_questions",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "rejected_questions",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "recommended_tools",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("family", name=op.f("agent_families_pkey")),
    )
    op.create_table(
        "output_modifications",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("proyecto_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("modified_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("agent_output_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_request", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("rewritten_request", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("recommended", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "recommendation_reason", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "recommendation_confidence",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "original_content",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "modified_content",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "evidence_collected",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "verification_plan",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "applied",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "applied_at", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "wiped_tables",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "pipeline_restarted_from",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "creado_en",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["agent_output_id"],
            ["agent_outputs.id"],
            name=op.f("output_modifications_agent_output_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["usuarios.id"],
            name=op.f("output_modifications_modified_by_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
            name=op.f("output_modifications_proyecto_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("output_modifications_pkey")),
    )
    op.create_index(
        op.f("idx_modifications_proyecto"),
        "output_modifications",
        ["proyecto_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_modifications_output"),
        "output_modifications",
        ["agent_output_id"],
        unique=False,
    )
    op.create_table(
        "agent_outputs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("proyecto_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "output_table", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("output_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "agent_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "agent_family", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "agent_tier", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column(
            "version",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_final",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "prompt_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "prompt_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column("loop_log_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("iteration_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("parent_output_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "creado_en",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["loop_log_id"],
            ["agent_loop_logs.id"],
            name=op.f("agent_outputs_loop_log_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_output_id"],
            ["agent_outputs.id"],
            name=op.f("agent_outputs_parent_output_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
            name=op.f("agent_outputs_proyecto_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_outputs_pkey")),
    )
    op.create_index(
        op.f("idx_agent_outputs_ref"),
        "agent_outputs",
        ["output_table", "output_id"],
        unique=True,
    )
    op.create_index(
        op.f("idx_agent_outputs_proyecto"),
        "agent_outputs",
        ["proyecto_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_agent_outputs_agent"), "agent_outputs", ["agent_id"], unique=False
    )
    op.create_table(
        "agent_loop_logs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("proyecto_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "agent_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "pattern", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("iterations", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "total_tokens",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_cost_est",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "had_reasoning",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tool_calls",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "llm_calls",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("result_summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "started_at", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "finished_at", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "creado_en",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["proyecto_id"],
            ["proyectos.id"],
            name=op.f("agent_loop_logs_proyecto_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_loop_logs_pkey")),
    )
    op.create_index(
        op.f("idx_loop_logs_proyecto"), "agent_loop_logs", ["proyecto_id"], unique=False
    )
    op.create_index(
        op.f("idx_loop_logs_agent"), "agent_loop_logs", ["agent_id"], unique=False
    )
    op.drop_index(
        op.f("ix_incident_comparisons_proyecto_id"), table_name="incident_comparisons"
    )
    op.drop_table("incident_comparisons")
    op.drop_index(
        op.f("ix_memo_sorting_groups_attempt_id"), table_name="memo_sorting_groups"
    )
    op.drop_table("memo_sorting_groups")
    op.drop_index(
        op.f("ix_extracted_incidents_segmento_id"), table_name="extracted_incidents"
    )
    op.drop_index(
        op.f("ix_extracted_incidents_proyecto_id"), table_name="extracted_incidents"
    )
    op.drop_index(
        op.f("ix_extracted_incidents_documento_id"), table_name="extracted_incidents"
    )
    op.drop_table("extracted_incidents")
    op.drop_index(
        op.f("ix_memo_sorting_attempts_theoretical_code_id"),
        table_name="memo_sorting_attempts",
    )
    op.drop_index(
        op.f("ix_memo_sorting_attempts_proyecto_id"), table_name="memo_sorting_attempts"
    )
    op.drop_table("memo_sorting_attempts")
    op.drop_index(op.f("ix_incident_groups_proyecto_id"), table_name="incident_groups")
    op.drop_table("incident_groups")
    # ### end Alembic commands ###
